# Generated by Django 4.1.1 on 2022-12-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvtapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
            ],
        ),
    ]
